# Where should we write the GIF?
Output assets/img/vhs/search/search-query.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 16
Set Width 1200
Set Height 600

Hide Sleep 2s Show

# Start ...

# Pause for dramatic effect...
Sleep 300ms

# Type a command in the terminal.
Type `sail search query 'created: [now-30d TO now]' --indices events`

# Pause for dramatic effect...
Sleep 1s

# Run the command by pressing enter.
Enter 

# Admire the output for a bit.
Sleep 20s