# Where should we write the GIF?
Output assets/img/vhs/brewinstall.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 16
Set Width 1200
Set Height 600

Hide Sleep 1.5s Show

# Start ...

# Pause for dramatic effect...
Sleep 300ms

# Type a command in the terminal.
Type "brew install sailpoint-oss/homebrew-sailpoint-oss/sailpoint-cli"

# Pause for dramatic effect...
Sleep 500ms

# Run the command by pressing enter.
Enter 

# Pause for dramatic effect...
Sleep 20s