# Where should we write the GIF?
Output assets/img/vhs/Sail.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 14
Set Width 1200
Set Height 800

Hide Sleep 1.5s Show

# Start ...

# Pause for dramatic effect...
Sleep 300ms

# Type a command in the terminal.
Type "sail"

# Pause for dramatic effect...
Sleep 800ms

# Run the command by pressing enter.
Enter

# Admire the output for a bit.
Sleep 5s